module.exports = {
	GLOBAL_NO_DATA: 'No Data',
	GLOBAL_MAX_LEVEINSTEIN: 1337,
	WEBSITE: {
		ANIMEOUT: 'ANIMEOUT',
		ANIMELAND: 'ANIMELAND',
		CHIA_ANIME: 'CHIA-ANIME',
		GOGOANIME: 'GOGOANIME',
		ANIMEFREAK: 'ANIMEFREAK',
		ANIMEHEIGHT: 'ANIME8'
	}
};
